---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
...

  

